package GUI;

import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/*
 * @author Ahmet Oğuz Ergin
 */
public class StartFrame extends javax.swing.JFrame
{

    public StartFrame()
    {
        initComponents();
        setFocusableWindowState(false);

        setIcon();
        setPosition();
    }

    public void setPosition()
    {
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice defaultScreen = ge.getDefaultScreenDevice();
        Rectangle rect = defaultScreen.getDefaultConfiguration().getBounds();
        int x = (int) rect.getMaxX() - this.getWidth() +10 ;
        int y = (int) rect.getMaxY() - this.getHeight() - 50;
        this.setLocation(x, y);
    }

    public void btnKeyPress(String operationString)
    {
        String output = "...";
        try
        {
            Robot robot = new Robot();

            if (operationString == "İşlem")
            {
                robot.keyPress(KeyEvent.VK_F4);
                robot.keyRelease(KeyEvent.VK_F4);

                Thread.sleep(300);

                robot.keyPress(KeyEvent.VK_F5);
                robot.keyRelease(KeyEvent.VK_F5);

                Thread.sleep(300);

                robot.keyPress(KeyEvent.VK_F11);
                robot.keyRelease(KeyEvent.VK_F11);

                output = "[ F4 + F5 + F11 ] Pressed.";
            } else if (operationString == "Kayıt")
            {
                robot.keyPress(KeyEvent.VK_F5);
                robot.keyRelease(KeyEvent.VK_F5);

                Thread.sleep(300);

                robot.keyPress(KeyEvent.VK_F10);
                robot.keyRelease(KeyEvent.VK_F10);

                output = "[ F5 + F10 ] Pressed.";
            } else if (operationString == "Onay")
            {
                robot.keyPress(KeyEvent.VK_F5);
                robot.keyRelease(KeyEvent.VK_F5);

                Thread.sleep(300);

                robot.keyPress(KeyEvent.VK_F2);
                robot.keyRelease(KeyEvent.VK_F2);

                Thread.sleep(300);

                robot.keyPress(KeyEvent.VK_F12);
                robot.keyRelease(KeyEvent.VK_F12);

                output = "[ F5 + F2 + F12 ] Pressed.";
            } else if (operationString == "Panel")
            {
                robot.keyPress(KeyEvent.VK_WINDOWS);
                robot.keyPress(KeyEvent.VK_V);
                
                Thread.sleep(100);

                robot.keyRelease(KeyEvent.VK_WINDOWS);
                robot.keyRelease(KeyEvent.VK_V);

                output = "[ Win + V ] Pressed.";
            }

            labelInfo.setText(output);

        } catch (Exception e)
        {
            setInfotext("Error");
        }
    }

    public void setInfotext(String msg)
    {
        labelInfo.setText(msg);
    }

    public void setIcon()
    {
        //ImageIcon img = new ImageIcon("/icon/favicon.png");
        //this.setIconImage(img.getImage());
        setIconImage((new ImageIcon(getClass().getResource("/icon/favicon.png"))).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        labelInfo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnCopy = new javax.swing.JButton();
        btnPaste = new javax.swing.JButton();
        btnPaste1 = new javax.swing.JButton();
        btnPaste2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Key Combinations");
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setFocusable(false);

        labelInfo.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        labelInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInfo.setText("... Thanks to Tiko ...");
        labelInfo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setFocusable(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(383, 30));

        btnCopy.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnCopy.setText("İşlem");
        btnCopy.setFocusable(false);
        btnCopy.setMaximumSize(new java.awt.Dimension(60, 25));
        btnCopy.setPreferredSize(new java.awt.Dimension(61, 25));
        btnCopy.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                genericBtnClick(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btnMouseEnter(evt);
            }
        });
        btnCopy.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCopyActionPerformed(evt);
            }
        });

        btnPaste.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnPaste.setText("Kayıt");
        btnPaste.setFocusable(false);
        btnPaste.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                genericBtnClick(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btnMouseEnter(evt);
            }
        });
        btnPaste.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnPasteActionPerformed(evt);
            }
        });

        btnPaste1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnPaste1.setText("Onay");
        btnPaste1.setFocusable(false);
        btnPaste1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                genericBtnClick(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btnMouseEnter(evt);
            }
        });

        btnPaste2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnPaste2.setText("Panel");
        btnPaste2.setFocusable(false);
        btnPaste2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                genericBtnClick(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btnMouseEnter(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPaste, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPaste1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPaste2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(btnPaste1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnPaste2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnPaste, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(labelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void genericBtnClick(java.awt.event.MouseEvent evt)//GEN-FIRST:event_genericBtnClick
    {//GEN-HEADEREND:event_genericBtnClick
        Object obj = evt.getSource();
        JButton btn = (JButton) obj;
        String btnText = btn.getText();
        btnKeyPress(btnText);
    }//GEN-LAST:event_genericBtnClick

    private void btnCopyActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCopyActionPerformed
    {//GEN-HEADEREND:event_btnCopyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCopyActionPerformed

    private void btnMouseEnter(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnMouseEnter
    {//GEN-HEADEREND:event_btnMouseEnter
        Object obj = evt.getSource();
        JButton btn = (JButton) obj;
        String btnText = btn.getText();

        if (btnText.equalsIgnoreCase("İşlem"))
        {
            setInfotext("F4 + F5 + F11");
        } else if (btnText.equalsIgnoreCase("Kayıt"))
        {
            setInfotext("F5 + F10");
        } else if (btnText.equalsIgnoreCase("Onay"))
        {
            setInfotext("F5 + F2 + F12");
        } else if (btnText.equalsIgnoreCase("Panel"))
        {
            setInfotext("Win + V");
        }
    }//GEN-LAST:event_btnMouseEnter

    private void btnPasteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnPasteActionPerformed
    {//GEN-HEADEREND:event_btnPasteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPasteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new StartFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCopy;
    private javax.swing.JButton btnPaste;
    private javax.swing.JButton btnPaste1;
    private javax.swing.JButton btnPaste2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelInfo;
    // End of variables declaration//GEN-END:variables
}
