package GUI;

import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import static java.lang.Thread.sleep;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/*
 * @author Ahmet Oğuz Ergin
 */
public class StartFrame extends javax.swing.JFrame
{

    public StartFrame()
    {
        initComponents();
        
        setIcon();
        
        /*
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice defaultScreen = ge.getDefaultScreenDevice();
        Rectangle rect = defaultScreen.getDefaultConfiguration().getBounds();
        int x = (int) rect.getMaxX() - this.getWidth() + 10;
        int y = (int) rect.getMaxY() - this.getHeight() + 10;
        System.out.println(y);
        this.setLocation(x, y);
         */
    }

    public void btnKeyPress(String operationString)
    {
        String output = "...";
        try
        {
            Robot robot = new Robot();

            robot.keyPress(KeyEvent.VK_ALT);
            robot.keyPress(KeyEvent.VK_TAB);
            robot.keyRelease(KeyEvent.VK_TAB);
            robot.keyRelease(KeyEvent.VK_ALT);

            sleep(100);

            if (operationString == "Copy")
            {
                robot.keyPress(KeyEvent.VK_CONTROL);
                robot.keyPress(KeyEvent.VK_C);

                robot.keyRelease(KeyEvent.VK_CONTROL);
                robot.keyRelease(KeyEvent.VK_C);

                output = "[ Ctrl + C ] Pressed.";
            }
            else if (operationString == "Paste")
            {
                robot.keyPress(KeyEvent.VK_CONTROL);
                robot.keyPress(KeyEvent.VK_V);

                robot.keyRelease(KeyEvent.VK_CONTROL);
                robot.keyRelease(KeyEvent.VK_V);

                output = "[ Ctrl + V ] Pressed.";
            }

            labelInfo.setText(output);

        } catch (Exception e)
        {
            setInfotext("Error");
        }
    }

    public void setInfotext(String msg)
    {
        labelInfo.setText(msg);
    }
    
    public void setIcon(){
        //ImageIcon ico = new ImageIcon(".//res//icon//favicon.ico");
        //ImageIcon ico = new ImageIcon(getClass().getClassLoader().getResource("favicon.ico"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        labelInfo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnCopy = new javax.swing.JButton();
        btnPaste = new javax.swing.JButton();
        btnPaste1 = new javax.swing.JButton();
        btnPaste2 = new javax.swing.JButton();
        btnPaste4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(204, 255, 204));

        labelInfo.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        labelInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInfo.setText("... Thanks to Tiko ...");
        labelInfo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 40));

        btnCopy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCopy.setText("Copy");
        btnCopy.setFocusable(false);
        btnCopy.setMaximumSize(new java.awt.Dimension(60, 25));
        btnCopy.setPreferredSize(new java.awt.Dimension(61, 25));
        btnCopy.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseMoved(java.awt.event.MouseEvent evt)
            {
                btnCopyMouseMoved(evt);
            }
        });
        btnCopy.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnCopyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btnCopyMouseEntered(evt);
            }
        });
        btnCopy.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCopyActionPerformed(evt);
            }
        });

        btnPaste.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPaste.setText("Paste");
        btnPaste.setFocusable(false);
        btnPaste.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseMoved(java.awt.event.MouseEvent evt)
            {
                btnPasteMouseMoved(evt);
            }
        });
        btnPaste.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnPasteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btnPasteMouseEntered(evt);
            }
        });
        btnPaste.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnPasteActionPerformed(evt);
            }
        });

        btnPaste1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPaste1.setText("new");
        btnPaste1.setFocusable(false);
        btnPaste1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseMoved(java.awt.event.MouseEvent evt)
            {
                btnPaste1MouseMoved(evt);
            }
        });
        btnPaste1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnPaste1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btnPaste1MouseEntered(evt);
            }
        });

        btnPaste2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPaste2.setText("new");
        btnPaste2.setFocusable(false);
        btnPaste2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseMoved(java.awt.event.MouseEvent evt)
            {
                btnPaste2MouseMoved(evt);
            }
        });
        btnPaste2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnPaste2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btnPaste2MouseEntered(evt);
            }
        });

        btnPaste4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPaste4.setText("new");
        btnPaste4.setFocusable(false);
        btnPaste4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseMoved(java.awt.event.MouseEvent evt)
            {
                btnPaste4MouseMoved(evt);
            }
        });
        btnPaste4.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnPaste4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btnPaste4MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPaste, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(btnPaste1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btnPaste2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPaste4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(btnPaste1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnPaste2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnPaste, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnPaste4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCopyMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnCopyMouseClicked
    {//GEN-HEADEREND:event_btnCopyMouseClicked
        Object obj = evt.getSource();
        JButton btn = (JButton) obj;
        String btnText = btn.getText();
        btnKeyPress(btnText);
    }//GEN-LAST:event_btnCopyMouseClicked

    private void btnCopyMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnCopyMouseMoved
    {//GEN-HEADEREND:event_btnCopyMouseMoved

    }//GEN-LAST:event_btnCopyMouseMoved

    private void btnPasteMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnPasteMouseMoved
    {//GEN-HEADEREND:event_btnPasteMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPasteMouseMoved

    private void btnPasteMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnPasteMouseClicked
    {//GEN-HEADEREND:event_btnPasteMouseClicked
        Object obj = evt.getSource();
        JButton btn = (JButton) obj;
        String btnText = btn.getText();
        btnKeyPress(btnText);
    }//GEN-LAST:event_btnPasteMouseClicked

    private void btnCopyActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCopyActionPerformed
    {//GEN-HEADEREND:event_btnCopyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCopyActionPerformed

    private void btnCopyMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnCopyMouseEntered
    {//GEN-HEADEREND:event_btnCopyMouseEntered
        setInfotext("Ctrl + C");
    }//GEN-LAST:event_btnCopyMouseEntered

    private void btnPasteMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnPasteMouseEntered
    {//GEN-HEADEREND:event_btnPasteMouseEntered
        setInfotext("Ctrl + V");
    }//GEN-LAST:event_btnPasteMouseEntered

    private void btnPaste1MouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnPaste1MouseMoved
    {//GEN-HEADEREND:event_btnPaste1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPaste1MouseMoved

    private void btnPaste1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnPaste1MouseClicked
    {//GEN-HEADEREND:event_btnPaste1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPaste1MouseClicked

    private void btnPaste1MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnPaste1MouseEntered
    {//GEN-HEADEREND:event_btnPaste1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPaste1MouseEntered

    private void btnPaste2MouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnPaste2MouseMoved
    {//GEN-HEADEREND:event_btnPaste2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPaste2MouseMoved

    private void btnPaste2MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnPaste2MouseClicked
    {//GEN-HEADEREND:event_btnPaste2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPaste2MouseClicked

    private void btnPaste2MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnPaste2MouseEntered
    {//GEN-HEADEREND:event_btnPaste2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPaste2MouseEntered

    private void btnPasteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnPasteActionPerformed
    {//GEN-HEADEREND:event_btnPasteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPasteActionPerformed

    private void btnPaste4MouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnPaste4MouseMoved
    {//GEN-HEADEREND:event_btnPaste4MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPaste4MouseMoved

    private void btnPaste4MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnPaste4MouseClicked
    {//GEN-HEADEREND:event_btnPaste4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPaste4MouseClicked

    private void btnPaste4MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnPaste4MouseEntered
    {//GEN-HEADEREND:event_btnPaste4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPaste4MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new StartFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCopy;
    private javax.swing.JButton btnPaste;
    private javax.swing.JButton btnPaste1;
    private javax.swing.JButton btnPaste2;
    private javax.swing.JButton btnPaste4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelInfo;
    // End of variables declaration//GEN-END:variables
}
